name: flash_cart
description: "Premium Quick-Commerce App with Geofencing and Secret Management."
publish_to: 'none'
version: 1.0.8+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  pdf: ^3.11.1
  printing: ^5.13.2
  shared_preferences: ^2.3.5
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0F172A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/app_icon.png
    - assets/logo.png
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/headerfont.ttf
        - asset: assets/fonts/menufont.ttf
          weight: 700
